name: Extract Secrets
on: workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secrets
        run: |
          echo "AMPLITUDE_API_KEY: $(echo "${{ secrets.AMPLITUDE_API_KEY }}" | base64)"
          echo "QONVERSION_PROJECT_KEY: $(echo "${{ secrets.QONVERSION_PROJECT_KEY }}" | base64)"
          echo "SENTRY_DSN: $(echo "${{ secrets.SENTRY_DSN }}" | base64)"
          echo "APPSFLYER_DEV_KEY: $(echo "${{ secrets.APPSFLYER_DEV_KEY }}" | base64)"
          echo "APPSFLYER_APP_ID: $(echo "${{ secrets.APPSFLYER_APP_ID }}" | base64)"
          
          # Bundle IDs 
          echo "IOS_BUNDLE_ID: $(echo "${{ secrets.IOS_BUNDLE_ID }}" | base64)"
          echo "ANDROID_PACKAGE_NAME: $(echo "${{ secrets.ANDROID_PACKAGE_NAME }}" | base64)"
          
          echo "GOOGLE_SERVICES_ANDROID: ${{ secrets.ANDROID_GOOGLE_SERVICES_JSON_BASE64 }}"
          echo "GOOGLE_SERVICES_IOS: ${{ secrets.IOS_GOOGLE_SERVICE_INFO_PLIST_BASE64 }}"
